name: CI for Document Conversion App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install frontend dependencies
      run: cd frontend && npm install

    - name: Lint frontend code
      run: cd frontend && npm run lint

    - name: Build React app
      run: cd frontend && npm run build

    - name: Run frontend tests
      run: cd frontend && npm test # Assuming you have tests configured

  build-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install backend dependencies
      run: cd backend && npm install

    - name: Lint backend code
      run: cd backend && npm run lint

    # Placeholder for running backend tests
    - name: Run backend tests
      run: echo "Run your backend tests here"
