name: CI for Document Conversion App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install frontend dependencies
        run: cd frontend && npm install
      - name: Lint frontend code
        run: cd frontend && npm run lint

  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install backend dependencies
        run: cd backend && npm install
      - name: Lint backend code
        run: cd backend && npx eslint . --ext .js,.jsx

  lint-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Lambda dependencies
        run: cd lambda && npm install
      - name: Lint Lambda function code
        run: cd lambda && npx eslint . --ext .js,.jsx

  # Add other jobs for building/testing as needed
